version: '2'

volumes:
    logs:
        driver: local

services:
    slim:
        image: ulsmith/alpine-apache-php7
        working_dir: /app
        environment:
            docker: "true"
        ports:
            - 8080:80
        volumes:
            - ./:/app
            - logs:/var/www/logs
        environment:
            - APACHE_SERVER_NAME=catalogue.docker.localhost
            - PHP_SHORT_OPEN_TAG=On
            - PHP_ERROR_REPORTING=E_ALL
            - PHP_DISPLAY_ERRORS=On
            - PHP_HTML_ERRORS=On
            - PHP_XDEBUG_ENABLED=true
        networks:
            - default
        cap_add:
            - SYS_TIME
            - SYS_NICE
        build: ./
