version: '2'

volumes:
    logs:
        driver: local

services:
    slim:
        image: ulsmith/alpine-apache-php7
        working_dir: /app
        environment:
            docker: "true"
        ports:
            - 8092:80
        volumes:
            - ./:/app
            - logs:/var/www/logs
        environment:
            - APACHE_SERVER_NAME=novoafrica.docker.localhost
            - PHP_SHORT_OPEN_TAG=On
            - PHP_ERROR_REPORTING=E_ALL
            - PHP_DISPLAY_ERRORS=On
            - PHP_HTML_ERRORS=On
            - PHP_XDEBUG_ENABLED=false
            - DB_HOST=192.168.0.205
            - DB_USER=root
            - DB_PASS=charles
            - DB_NAME=novo_africa

        networks:
            - default
        cap_add:
            - SYS_TIME
            - SYS_NICE
        build: ./
